---
services:
  uptime:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:${UPTIME_VERSION}
    # ports:
      # - 3001:3001
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.uptime.rule=Host(`uptime.igarashimountain.com`)"
      - "traefik.http.routers.uptime.entrypoints=https"
      - "traefik.http.routers.uptime.tls=true"
      - "traefik.http.services.uptime.loadbalancer.server.port=3001"  
    networks:
      - proxy
    volumes:
      - ./data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

networks:
  proxy:
    external: true
