---
services:
  frontend:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:1
    ports:
      - 3001:3001
    volumes:
      - ./frontend:/app/data
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
