---
- name: Backup Docker volumes for all services
  hosts: "services"
  become: yes
  vars_files:
  - ~/.ansible/vault/ansible_become_pass.yml
  roles:
  - role: docker/compose_backup
    vars:
      stack_name: "open_webui"

  - role: docker/compose_backup
    vars:
      stack_name: "jellyfin"
