---
- name: Tear down the Open Web UI stack of Docker containers
  hosts: "services"
  vars_files:
  - ~/.ansible/vault/ansible_become_pass.yml
  roles:
  - role: docker/compose_down
    become: yes
    vars:
      stack_name: "open_webui"
