---
- name: Tear down all of the service stacks of Docker containers
  hosts: "services"
  become: yes
  vars_files:
  - ~/.ansible/vault/ansible_become_pass.yml
  roles:
  - role: docker/compose_down
    vars:
      stack_name: "uptime_kuma"

  - role: docker/compose_down
    vars:
      stack_name: "open_webui"

  - role: docker/compose_down
    vars:
      stack_name: "mealie"

  # - role: docker/compose_down
  #   vars:
  #     stack_name: "jellyfin"

  - role: docker/compose_down
    vars:
      stack_name: "homepage"

  # - role: docker/compose_down
  #   vars:
  #     stack_name: "change_detection"

  - role: docker/compose_down
    vars:
      stack_name: "actual"

  - role: docker/compose_down
    vars:
      stack_name: "traefik"
