---
- name: Pull the latest Docker images for all services
  hosts: "services"
  vars_files:
  - ~/.ansible/vault/ansible_become_pass.yml
  roles:
  - role: docker/compose_pull
    become: yes
    vars:
      stack_name: "open_webui"

  - role: docker/compose_pull
    become: yes
    vars:
      stack_name: "jellyfin"
