---
- name: Tear down the rclone stack of Docker containers
  hosts: "services"
  become: yes
  vars_files:
  - ~/.ansible/vault/ansible_become_pass.yml
  roles:
  - role: docker/compose_down
    vars:
      stack_name: "rclone"
