---
- name: Restore most recent Docker volume for all services
  hosts: "services"
  become: yes
  vars_files:
  - ~/.ansible/vault/ansible_become_pass.yml
  roles:
  # - role: docker/compose_restore
  #   vars:
  #     stack_name: "open_webui"

  # - role: docker/compose_restore
  #   vars:
  #     stack_name: "jellyfin"
