---
- name: Deploy the Jellyfin stack of Docker containers
  hosts: "services"
  become: yes
  vars_files:
  - ~/.ansible/vault/ansible_become_pass.yml
  roles:
  - role: docker/compose_up
    vars:
      stack_name: "open_webui"

  - role: docker/compose_up
    vars:
      stack_name: "jellyfin"

  - role: docker/compose_up
    vars:
      stack_name: "actual"

  - role: docker/compose_up
    vars:
      stack_name: "change_detection"
