---
- name: Deploy the Pihole stack of Docker containers
  hosts: "lxcpihole"
  become: yes
  vars_files:
  - ~/.ansible/vault/ansible_become_pass.yml
  roles:
  - role: docker/compose_up
    vars:
      stack_name: "pihole"
