---
- name: Tear down the essential service stacks of Docker containers
  hosts: "essentials"
  become: yes
  vars_files:
  - ~/.ansible/vault/ansible_become_pass.yml
  roles:
  - role: docker/compose_down
    vars:
      stack_name: "homepage"

  - role: docker/compose_down
    vars:
      stack_name: "uptime_kuma"

  - role: docker/compose_down
    vars:
      stack_name: "traefik"
