---
services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:${HA_VERSION}
    container_name: homeassistant
    depends_on:
      - mqtt
      - zigbee2mqtt
    networks:
      # iot_macvlan:
      #   ipv4_address: 192.168.20.36
      proxy:
    ports:
      - 8123:8123
    volumes:
      - ./homeassistant/config:/config
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.homeassistant.rule=Host(`homeassistant.igarashimountain.com`)"
      - "traefik.http.routers.homeassistant.entrypoints=https"
      - "traefik.http.routers.homeassistant.tls=true"
      - "traefik.http.services.homeassistant.loadbalancer.server.port=8123"  
      - "traefik.http.routers.homeassistant.middlewares=default-headers@file"
    restart: unless-stopped

  mqtt:
    image: eclipse-mosquitto:${MQTT_VERSION}
    container_name: mqtt
    networks:
      - proxy
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
    volumes:
      - ./mqtt/data:/mosquitto
    command: mosquitto -c /mosquitto-no-auth.conf
    restart: unless-stopped

  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:${Z2MQTT_VERSION}
    container_name: zigbee2mqtt
    networks:
      iot_macvlan:
        ipv4_address: 192.168.20.37
      proxy:
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.zigbee2mqtt.rule=Host(`zigbee2mqtt.igarashimountain.com`)"
      - "traefik.http.routers.zigbee2mqtt.entrypoints=https"
      - "traefik.http.routers.zigbee2mqtt.tls=true"
      - "traefik.http.services.zigbee2mqtt.loadbalancer.server.port=8080"  
    volumes:
      - ./zigbee2mqtt/data:/app/data
    restart: unless-stopped

networks:
  proxy:
    external: true
  iot_macvlan:
    external: true
