---
services:
  gluetun:
    image: qmcgaw/gluetun:${GLUETUN_VERSION}
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - SERVER_COUNTRIES=Canada
      - TZ=${TZ}
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8080:8080 # qBittorrent
      - 8989:8989 # Sonarr
      - 7878:7878 # Radarr
      - 8686:8686 # Lidarr
      - 8787:8787 # Readarr
      - 9696:9696 # Prowlarr
      - 8191:8191 # FlareSolverr
      - 6767:6767 # Bazarr
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:${QBITTORRENT_VERSION}
    container_name: qbittorrent
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ./qbittorrent:/config
      - smb-downloads:/downloads
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:${SONARR_VERSION}
    container_name: sonarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ./sonarr:/config
      - smb-downloads:/downloads
      - smb-tv:/tv
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:${RADARR_VERSION}
    container_name: radarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ./radarr:/config
      - smb-downloads:/downloads
      - smb-movies:/movies
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr:${LIDARR_VERSION}
    container_name: lidarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ./lidarr:/config
      - smb-downloads:/downloads
      - smb-music:/music 
    restart: unless-stopped

  readarr:
    image: lscr.io/linuxserver/readarr:${READARR_VERSION}
    container_name: readarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ./readarr:/config
      - smb-downloads:/downloads
      - smb-books:/books 
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:${PROWLARR_VERSION}
    container_name: prowlarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ./prowlarr:/config
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:${FLARESOLVERR_VERSION}
    container_name: flaresolverr
    network_mode: "service:gluetun"
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TZ}
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:${BAZARR_VERSION}
    container_name: bazarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ./bazarr:/config
      - smb-movies:/movies
      - smb-tv:/tv
    restart: unless-stopped

volumes:
  smb-downloads:
    driver: local
    driver_opts:
      type: cifs
      o: username=${SMB_USERNAME},password=${SMB_PASSWORD},rw
      device: "//${SMB_SHARE_IP}/entertainment/downloads"
  smb-tv:
    driver: local
    driver_opts:
      type: cifs
      o: username=${SMB_USERNAME},password=${SMB_PASSWORD},rw
      device: "//${SMB_SHARE_IP}/entertainment/tv"
  smb-movies:
    driver: local
    driver_opts:
      type: cifs
      o: username=${SMB_USERNAME},password=${SMB_PASSWORD},rw
      device: "//${SMB_SHARE_IP}/entertainment/movies"
  smb-music:
    driver: local
    driver_opts:
      type: cifs
      o: username=${SMB_USERNAME},password=${SMB_PASSWORD},rw
      device: "//${SMB_SHARE_IP}/entertainment/music"
  smb-books:
    driver: local
    driver_opts:
      type: cifs
      o: username=${SMB_USERNAME},password=${SMB_PASSWORD},rw
      device: "//${SMB_SHARE_IP}/entertainment/books"
