---
services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - SERVER_COUNTRIES=Brazil
      - TZ=${TZ}
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8080:8080 # qBittorrent
      - 8989:8989 # Sonarr
      - 7878:7878 # Radarr
      - 8686:8686 # Lidarr
      - 8787:8787 # Readarr
      - 9696:9696 # Prowlarr
      - 8191:8191 # FlareSolverr
      - 6767:6767 # Bazarr
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:4.6.5
    container_name: qbittorrent
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ./qbittorrent:/config
      - nfs-downloads:/downloads
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:4.0.8
    container_name: sonarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ./sonarr:/config
      - nfs-downloads:/downloads
      - nfs-tv:/tv
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:5.7.0
    container_name: radarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ./radarr:/config
      - nfs-downloads:/downloads
      - nfs-movies:/movies
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr:2.4.3
    container_name: lidarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ./lidarr:/config
      - nfs-downloads:/downloads
      - nfs-music:/music 
    restart: unless-stopped

  readarr:
    image: lscr.io/linuxserver/readarr:0.3.31-develop
    container_name: readarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ./readarr:/config
      - nfs-downloads:/downloads
      - nfs-books:/books 
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:1.20.1
    container_name: prowlarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ./prowlarr:/config
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:v3.3.21
    container_name: flaresolverr
    network_mode: "service:gluetun"
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TZ}
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:1.4.3
    container_name: bazarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ./bazarr:/config
      - nfs-movies:/movies
      - nfs-tv:/tv
    restart: unless-stopped

volumes:
  nfs-downloads:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_SHARE_IP},rw,nfsvers=4,soft
      device: ":/Multimedia/Downloads"
  nfs-tv:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_SHARE_IP},rw,nfsvers=4,soft
      device: ":/Multimedia/TV"
  nfs-movies:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_SHARE_IP},rw,nfsvers=4,soft
      device: ":/Multimedia/Movies"
  nfs-music:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_SHARE_IP},rw,nfsvers=4,soft
      device: ":/Multimedia/Music"
  nfs-books:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_SHARE_IP},rw,nfsvers=4,soft
      device: ":/Multimedia/Books"
