---
- hosts: "test_server"
  become: yes
  vars_files:
    - ~/.ansible/vault/ansible_become_pass.yml
  tasks:
    - name: apt update && upgrade
      apt: 
        update_cache: yes
        upgrade: 'yes'