---
services:
  frontend:
    image: ghcr.io/open-webui/open-webui:${OPENWEBUI_VERSION}
    container_name: open_webui_frontend
    # ports:
      # - "3000:8080"
    environment:
      - OPENAI_API_BASE_URLS=${OPENAI_URL};${PIPELINE_URL}
      - OPENAI_API_KEYS=${OPENAI_API_KEY};${PIPELINE_API_KEY}
      - OLLAMA_BASE_URL=${OLLAMA_URL}:11434
      - ENABLE_RAG_WEB_SEARCH=True
      - RAG_WEB_SEARCH_ENGINE=searxng
      - RAG_WEB_SEARCH_RESULT_COUNT=3
      - RAG_WEB_SEARCH_CONCURRENT_REQUESTS=10
      - SEARXNG_QUERY_URL=${SEARXNG_QUERY_URL}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.chat.rule=Host(`chat.igarashimountain.com`)"
      - "traefik.http.routers.chat.entrypoints=https"
      - "traefik.http.routers.chat.tls=true"
      - "traefik.http.services.chat.loadbalancer.server.port=8080"  
    networks:
      - open_webui
      - proxy
    volumes:
      - ./frontend_data:/app/backend/data
    restart: unless-stopped

  pipelines:
    image: ghcr.io/open-webui/pipelines:${PIPELINES_VERSION}
    container_name: open_webui_pipelines
    # ports:
      # - "9099:9099"
    volumes:
      - ./pipelines_data:/app/pipelines
    networks:
      - open_webui
      # - proxy
    restart: unless-stopped

networks:
  open_webui:
  proxy:
    external: true
