---
services:
  frontend:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui_frontend
    ports:
      - "3000:8080"
    environment:
      - OPENAI_API_BASE_URLS=${OPENAI_URL};${PIPELINE_URL}
      - OPENAI_API_KEYS=${OPENAI_API_KEY};${PIPELINE_API_KEY}
    volumes:
      - ./frontend:/app/backend/data
    restart: unless-stopped

  pipelines:
    image: ghcr.io/open-webui/pipelines:main
    container_name: open-webui_pipelines
    # ports:
      # - "9099:9099"
    volumes:
      - ./pipelines:/app/pipelines
    # extra_hosts:
      # - "host.docker.internal:host-gateway"
    restart: unless-stopped
