---
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:${PIHOLE_VERSION}
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '8080:80/tcp'
    environment:
      - TZ=${TZ}
      - WEBPASSWORD=${WEBPASS}
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped
