---
- name: Restore most recent docker volume backup on sandbox
  hosts: "docker_services"
  vars_files:
  - ~/.ansible/vault/ansible_become_pass.yml
  roles:
  - role: docker/docker_compose_restore
    become: yes
    vars:
      stack_name: "traefik"

  - role: docker/docker_compose_restore
    become: yes
    vars:
      stack_name: "uptime_kuma"

  - role: docker/docker_compose_restore
    become: yes
    vars:
      stack_name: "open_webui"

  - role: docker/docker_compose_restore
    become: yes
    vars:
      stack_name: "homepage"
