---
services:
  code-server:
    image: lscr.io/linuxserver/code-server:${CODESERVER_VERSION}
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - PASSWORD=${GUI_PASSWORD} #optional
      - HASHED_PASSWORD=${HASHED_PASSWORD} #optional
      - SUDO_PASSWORD=${SUDO_PASSWORD} #optional
      - SUDO_PASSWORD_HASH=${SUDO_HASHED} #optional
      - PROXY_DOMAIN=${DOMAIN_ADDRESS} #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
    volumes:
      - ./config:/config
      - ${DEFAULT_WORKSPACE}:/config/workspace
    ports:
      - 8443:8443
    restart: unless-stopped
