services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:${MEALIE_VERSION}
    container_name: mealie
    # ports:
      # - "9925:9000"
    deploy:
      resources:
        limits:
          memory: 1000M
    volumes:
      - ./mealie:/app/data/
    environment:
      ALLOW_SIGNUP: false
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      MAX_WORKERS: 1
      WEB_CONCURRENCY: 1
      BASE_URL: ${MEALIE_URL}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.mealie.rule=Host(`mealie.igarashimountain.com`)"
      - "traefik.http.routers.mealie.entrypoints=https"
      - "traefik.http.routers.mealie.tls=true"
      - "traefik.http.services.mealie.loadbalancer.server.port=9000"  
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    external: true
