---
- name: Ensure the Sandbox stack of Docker containers are up to date on target
  hosts: "sandbox"
  vars_files:
  - ~/.ansible/vault/ansible_become_pass.yml
  roles:
  - role: docker_prune
    become: yes
