---
- name: Tear down the Sandbox stack of Docker containers on target
  hosts: "sandbox"
  vars_files:
  - ~/.ansible/vault/ansible_become_pass.yml
  roles:
  - role: docker/docker_compose_down
    become: yes
    vars:
      stack_name: "jellyfin"
