---
- name: Ensure the Sandbox stack of Docker containers up to date on target
  hosts: "sandbox"
  vars_files:
  - ~/.ansible/vault/ansible_become_pass.yml
  roles:
  - role: docker/docker_compose_up
    become: yes
    vars:
      stack_name: "jellyfin"
