---
- name: Restore most recent docker volume backup on sandbox
  hosts: "sandbox"
  vars:
    user_home: "/home/justin"
  vars_files:
  - ~/.ansible/vault/ansible_become_pass.yml
  roles:
  - role: docker/docker_compose_restore
    become: yes
    vars:
      stack_name: "uptime_kuma"

  - role: docker/docker_compose_restore
    become: yes
    vars:
      stack_name: "open_webui"
