---
- name: Tear down the Sandbox stack of Docker containers on target
  hosts: "sandbox"
  become: yes
  vars:
    stack_name: "change_detection"
  vars_files:
  - ~/.ansible/vault/ansible_become_pass.yml
  roles:
  - role: docker/compose_down
