---
- name: Ensure the Sandbox stack of Docker containers up to date on target
  hosts: "sandbox"
  become: yes
  vars:
    stack_name: "obsidian"
  vars_files:
  - ~/.ansible/vault/ansible_become_pass.yml
  roles:
  - role: docker/compose_up
az