---
- name: Ensure at least one file exists at /etc/netplan
  stat:
    path: "/etc/netplan"
  register: network_config_exists

- name: Check if 50-cloud-init.yaml file exists
  stat:
    path: "/etc/netplan/50-cloud-init.yaml"
  when: network_config_exists
  register: network_config

# - name: Debug backup volumes
#   debug:
#     msg: "{{ network_config }}"
    
- name: Copy network configuration template to remote server
  template:
    src: network_config.j2
    dest: "/etc/netplan/50-cloud-init.yaml"
  when: network_config

- name: Apply Netplan configuration
  command: netplan apply
  become: yes
  async: 1
  poll: 0
