---
services:
  actual:
    image: actualbudget/actual-server:24.7.0-alpine
    container_name: actual
    # ports:
    #   - "5006:5006"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.actual.rule=Host(`actual.igarashimountain.com`)"
      - "traefik.http.routers.actual.entrypoints=https"
      - "traefik.http.routers.actual.tls=true"
      - "traefik.http.services.actual.loadbalancer.server.port=5006"  
    networks:
      - proxy
    volumes:
      - ./actual:/data
    restart: unless-stopped

networks:
  proxy:
    external: true
