---
- name: Restore most recent Docker volume for all services
  hosts: "servarr"
  become: yes
  vars_files:
  - ~/.ansible/vault/ansible_become_pass.yml
  roles:
  - role: docker/compose_restore
    vars:
      stack_name: "servarr"
